sudo: true
language: java
cache:
  directories:
    - $HOME/.m2
    - .cpcache
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.375.sh
  - chmod +x linux-install-1.9.0.375.sh
  - sudo ./linux-install-1.9.0.375.sh
script:
  - clojure -Atest
  - mkdir target
  - clojure -Adots > target/install.sh
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target
  target-branch: install
  on:
    branch: master
