sudo: true
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - .cpcache
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.375.sh
  - chmod +x linux-install-1.9.0.375.sh
  - sudo ./linux-install-1.9.0.375.sh
script:
  - mkdir target
  - clojure dots.clj -s > target/install.sh
  - cat target/install.sh | HOME=test SKIP_RESTARTS=1 bash
  - '[[ $(find test -type f | wc -l) != 0 ]]'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target
  target-branch: install
  on:
    branch: master
